# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'ihs-hackathon-hs2' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ihs-hackathon-hs2
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'

end
