# Generated by Django 2.0.4 on 2018-04-14 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startData', models.DateTimeField()),
                ('endData', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Floors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pulse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StepSessions',
            fields=[
                ('exercise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='friends_workout.Exercise')),
                ('calories', models.ForeignKey(blank=True, null=True, on_delete=True, to='friends_workout.Calories')),
                ('distance', models.ForeignKey(blank=True, null=True, on_delete=True, to='friends_workout.Distance')),
                ('floors', models.ForeignKey(blank=True, null=True, on_delete=True, to='friends_workout.Floors')),
                ('pulse', models.ForeignKey(blank=True, null=True, on_delete=True, to='friends_workout.Pulse')),
                ('steps', models.ForeignKey(blank=True, null=True, on_delete=True, to='friends_workout.Steps')),
            ],
            bases=('friends_workout.exercise',),
        ),
    ]
