# Generated by Django 2.0.4 on 2018-04-14 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friends_workout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stepsessions',
            name='calories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='friends_workout.Calories'),
        ),
        migrations.AlterField(
            model_name='stepsessions',
            name='distance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='friends_workout.Distance'),
        ),
        migrations.AlterField(
            model_name='stepsessions',
            name='floors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='friends_workout.Floors'),
        ),
        migrations.AlterField(
            model_name='stepsessions',
            name='pulse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='friends_workout.Pulse'),
        ),
        migrations.AlterField(
            model_name='stepsessions',
            name='steps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='friends_workout.Steps'),
        ),
    ]
